// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl5T5BBElN1Uac6T9lIkpAC4dCVoDhajU',
    appId: '1:873903456607:web:196f0f820b670f97b5f6ea',
    messagingSenderId: '873903456607',
    projectId: 'apptask-management',
    authDomain: 'apptask-management.firebaseapp.com',
    storageBucket: 'apptask-management.appspot.com',
    measurementId: 'G-JKJJQK412Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vKMeiGo2XrdY30gszw5q0Jcuc74Jap8',
    appId: '1:873903456607:android:5ce9364e4c27d29eb5f6ea',
    messagingSenderId: '873903456607',
    projectId: 'apptask-management',
    storageBucket: 'apptask-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOU6j3SJGEz_ai7pt_L0LJW8OQ-8DyvZo',
    appId: '1:873903456607:ios:4e78c4da2fd7690eb5f6ea',
    messagingSenderId: '873903456607',
    projectId: 'apptask-management',
    storageBucket: 'apptask-management.appspot.com',
    androidClientId: '873903456607-kmj2ut15k5dcpjijqosmgvpsc4lpc2c1.apps.googleusercontent.com',
    iosClientId: '873903456607-red2irgtmb9gsmtgqvfs93rijast8cmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );
}
